sudo apt-get install -y ros-noetic-rosbash
sudo apt-get install -y ros-noetic-imu-filter-madgwick
sudo apt-get install -y ros-noetic-joy
sudo apt-get install -y ros-noetic-move-base
sudo apt-get install -y ros-noetic-dwa-local-planner
sudo apt-get install -y ros-noetic-map-server
sudo apt-get install -y ros-noetic-amcl
sudo apt-get install -y ros-noetic-robot-localization
sudo apt-get install -y ros-noetic-slam-gmapping
sudo apt-get install -y ros-noetic-rosserial-python
sudo apt-get install -y ros-noetic-xacro 
sudo apt-get install -y ros-noetic-joint-state-publisher
sudo apt-get install -y ros-noetic-robot-state-publisher
sudo apt-get install -y ros-noetic-aruco-ros
sudo apt-get install -y ros-noetic-global-planner
sudo apt-get install -y ros-noetic-controller-manager
sudo apt-get install -y ros-noetic-joint-limits-interface
sudo apt-get install -y ros-noetic-rospy-tutorials 
sudo apt-get install -y ros-noetic-rplidar-ros
sudo apt-get install -y ros-noetic-diff-drive-controller
sudo apt-get install -y ros-noetic-joint-state-controller